apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: backup-test
spec:
  cluster:
    name: cluster-example
  target: "primary"
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
